/* eslint-disable max-len */
import { Item, ItemRarities } from "./itemTypes";

export const info: Record<string, Item> = {
	"ap_rounds": {
		name: "Armor-Piercing Rounds",
		description: [
			"sta::Deal an additional ",
			"yel::20% ",
			"sta::damage ",
			"gra::(+20% per stack) ",
			"sta::to bosses"
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/f0/Armor-Piercing_Rounds.png",
		rarity: ItemRarities.WHITE,
		challenge: "Complete a Teleporter event.",
		scaling: "Linear",
	},
	"backup_mag": {
		name: "Backup Magazine",
		description: [
			"sta::Add ",
			"blu::+1 ",
			"gra::(+1 per stack) ",
			"sta::charge of your ",
			"blu::Secondary Skill",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/f3/Backup_Magazine.png",
		rarity: ItemRarities.WHITE,
		challenge: "Fully charge a Teleporter without getting hit.",
		scaling: "Linear",
	},
	"bison_steak": {
		name: "Bison Steak",
		description: [
			"sta::Increases ",
			"gre::maximum Health ",
			"sta::by ",
			"gre::25 ",
			"gra::(+25 per stack)",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/9/9f/Bison_Steak.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"fireworks": {
		name: "Bundle of Fireworks",
		description: [
			"sta::Activating an interactable ",
			"yel::launches 8 ",
			"gra::(+4 per stack) ",
			"yel::fireworks ",
			"sta::that deal ",
			"yel::300% ",
			"sta::base damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/3d/Bundle_of_Fireworks.png",
		rarity: ItemRarities.WHITE,
		challenge: "Duplicate the same item 7 times in a row with a 3D Printer.",
		scaling: "Linear",
		proc_coefficient: "0.2",
	},
	"bustling_fungus": {
		name: "Bustling Fungus",
		description: [
			"sta::After standing still for ",
			"gre::1 ",
			"sta::second, create a zone that ",
			"gre::heals for 4.5% ",
			"gra::(+2.25% per stack) ",
			"sta::of your ",
			"gre::health ",
			"sta::every second to all allies within ",
			"gre::3m ",
			"gra::(+1.5m per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/33/Bustling_Fungus.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"cautious_slug": {
		name: "Cautious Slug",
		description: [
			"sta::Increases ",
			"gre::base health regeneration ",
			"sta::by ",
			"gre::3 hp/s ",
			"gra::(+3 hp/s per stack) ",
			"sta::while outside of combat", 
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c6/Cautious_Slug.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"crowbar": {
		name: "Crowbar",
		description: [
			"sta::Deal ",
			"yel::+75% ",
			"gra::(+75% per stack) ",
			"sta::damage to enemies above ",
			"yel::90% health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c0/Crowbar.png",
		rarity: ItemRarities.WHITE,
		challenge: "Discover 10 unique white items.",
		scaling: "Linear",
	},
	"energy_drink": {
		name: "Energy Drink",
		description: [
			"blu::Sprint speed ",
			"sta::is improved by ",
			"blu::25% ",
			"gra::(+25% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/7e/Energy_Drink.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"focus_crystal": {
		name: "Focus Crystal",
		description: [
			"sta::Increase damage to enemies within ",
			"yel::13m ",
			"sta::by ",
			"yel::20% ",
			"gra::(+20% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/5/59/Focus_Crystal.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"gasoline": {
		name: "Gasoline",
		description: [
			"sta::Killing an enemy ",
			"yel::ignites ",
			"sta::all enemies within ",
			"yel::12m ",
			"gra::(+4m per stack) ",
			"yel::for 150% ",
			"sta::base damage. Additionally, enemies ",
			"yel::burn ",
			"sta::for ",
			"yel::150% ",
			"gra::(+75% per stack) ",
			"sta::base damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/6e/Gasoline.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"lens_makers_glasses": {
		name: "Len's Makers Glasses",
		description: [
			"sta::Your attacks have a ",
			"yel::10% ",
			"gra::(+10% per stack) ",
			"sta::chance to ",
			"yel::'Critically Strike', ", 
			"sta::dealing ",
			"yel::double damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/23/Lens-Maker%27s_Glasses.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"medkit": {
		name: "Medkit",
		description: [
			"sta::2 seconds after getting hurt, ",
			"gre::heal ",
			"sta::for ",
			"gre::20 ",
			"sta::plus an additional ",
			"gre::5% ",
			"gra::(+5% per stack) ",
			"sta::of ",
			"gre::maximum health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/0f/Medkit.png",
		rarity: ItemRarities.WHITE,
		challenge: "Defeat an Elite-type monster.",
		scaling: "Linear",
	},
	"monster_tooth": {
		name: "Monster Tooth",
		description: [
			"sta::Killing an enemy spawns a ",
			"gre::healing orb ",
			"sta::that heals for ",
			"gre::8 ",
			"sta::plus an additional ",
			"gre::2% ",
			"gra::(+2% per stack) ",
			"sta::of ",
			"gre::maximum health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/3b/Monster_Tooth.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"goat_hoof": {
		name: "Paul's Goat Hoof",
		description: [
			"sta::Increases ",
			"blu::movement speed ",
			"sta::by ",
			"blu::14% ",
			"gra::(+14% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/4/4a/Paul%27s_Goat_Hoof.png",
		rarity: ItemRarities.WHITE,
		challenge: "Fail the Shrine of Chance 3 times in a row.",
		scaling: "Linear",
	},
	"personal_shield_gen": {
		name: "Personal Shield Generator",
		description: [
			"sta::Gain a ",
			"gre::shield ",
			"sta::equal to ",
			"gre::8% ",
			"gra::(+8% per stack) ",
			"sta::of your maximum health. Recharges outside of danger",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e0/Personal_Shield_Generator.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"armor_plate": {
		name: "Repulsion Armor Plate",
		description: [
			"sta::Reduce all ",
			"yel::incoming damage ",
			"sta::by ",
			"yel::5 ",
			"gra::(+5 per stack)",
			"sta::. Cannot be reduced below ",
			"yel::1",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/a/aa/Repulsion_Armor_Plate.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"rusted_key": {
		name: "Rusted Key",
		description: [
			"sta::A ",
			"blu::hidden cache ",
			"sta::containing an item (",
			"gre::80%",
			"sta::/",
			"red::20%",
			"sta::) will appear in a random location ",
			"blu::on each stage",
			"sta::. Opening the cache ",
			"blu::consumes ",
			"sta::this item",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/9/9b/Rusted_Key.png",
		rarity: ItemRarities.WHITE,
		challenge: "Defeat the Teleporter boss under 15 seconds.",
		scaling: "Linear",
	},
	"soldiers_syringe": {
		name: "Soldier's Syringe",
		description: [
			"sta::Increases ",
			"yel::attack speed ",
			"sta::by ",
			"yel::15% ",
			"gra::(+15% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/f2/Soldier%27s_Syringe.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"sticky_bomb": {
		name: "Sticky Bomb",
		description: [
			"yel::5% ",
			"gra::(+5% per stack) ",
			"sta::chance on hit to attach a ",
			"yel::bomb ",
			"sta::to an enemy, detonating for ",
			"yel::180% ",
			"sta::TOTAL damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/74/Sticky_Bomb.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"stun_grenade": {
		name: "Stun Grenade",
		description: [
			"blu::5% ",
			"gra::(+5% on stack) ",
			"sta::chance on hit to ",
			"blu::stun ",
			"sta::enemies for ",
			"blu::2 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/27/Stun_Grenade.png",
		rarity: ItemRarities.WHITE,
		scaling: "Hyperbolic",
	},
	"topaz_brooch": {
		name: "Topaz Brooch",
		description: [
			"sta::Gain a ",
			"gre::temporary barrier ",
			"sta::on kill for ",
			"gre::15 health ",
			"gra::(+15 per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c5/Topaz_Brooch.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"tougher_times": {
		name: "Tougher Times",
		description: [
			"gre::15% ",
			"gra::(+15% per stack) ",
			"sta::chance to ",
			"gre::block ",
			"sta::incoming damage. ",
			"blu::Unaffected by luck",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/39/Tougher_Times.png",
		rarity: ItemRarities.WHITE,
		challenge: "Die 5 times.",
		scaling: "Hyperbolic",
	},
	"tritip_dagger": {
		name: "Tri-Tip Dagger",
		description: [
			"yel::10% ",
			"gra::(+10% per stack) ",
			"sta::chance to ",
			"yel::bleed ",
			"sta::an enemy for ",
			"yel::240% ",
			"sta::base damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/1/17/Tri-Tip_Dagger.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"warbanner": {
		name: "Warbanner",
		description: [
			"sta::On ",
			"blu::level up ",
			"sta::or starting the ",
			"blu::Teleporter event",
			"sta::, drop a banner that strengthens all allies within ",
			"blu::16m ",
			"gra::(+8m per stack)",
			"sta::. Raises ",
			"yel::attack ",
			"sta::and ",
			"blu::movement speed ",
			"sta::by ",
			"yel::30% ",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/f0/Warbanner.png",
		rarity: ItemRarities.WHITE,
		scaling: "Linear",
	},
	"item_scrap_white": {
		name: "Item Scrap, White",
		description: [
			"sta::Does nothing. Prioritized when used with 3D Printers",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/9/99/Item_Scrap%2C_White.png",
		rarity: ItemRarities.WHITE,
	},
	"atg_missile": {
		name: "AtG Missile Mk. 1",
		description: [
			"yel::10% ",
			"sta::chance to fire a missile that deals ",
			"yel::300% ",
			"gra::(+300% per stack) ",
			"sta::TOTAL damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/6a/AtG_Missile_Mk._1.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
		proc_coefficient: "1",
	},
	"bandolier": {
		name: "Bandolier",
		description: [
			"blu::18% ",
			"gra::(+10% per stack) ",
			"sta::chance on kill to drop an ammo pack that ",
			"blu::resets all skill cooldowns",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/62/Bandolier.png",
		rarity: ItemRarities.GREEN,
		scaling: "Special",
	},
	"berzerkers_pauldron": {
		name: "Berzerker's Pauldron",
		description: [
			"yel::Killing 3 enemies ",
			"sta::within ",
			"yel::1 ",
			"sta::second sends you into a frenzy for",
			"yel::6s ",
			"gra::(+4s per stack)",
			"sta::. Increases ",
			"blu::movement speed ",
			"sta::by ",
			"blu::50% ",
			"sta::and ",
			"yel::attack speed ",
			"sta::by ",
			"yel::100%",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/a/a6/Berzerker%27s_Pauldron.png",
		rarity: ItemRarities.GREEN,
		challenge: "Charge the Teleporter with less than 10% health.",
		scaling: "Linear",
	},
	"chronobauble": {
		name: "Chronobauble",
		description: [
			"blu::Slow ",
			"sta::enemies on hit for ",
			"blu::-60% movement speed ",
			"sta::for ",
			"blu::2s ",
			"gra::(+2s per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/38/Chronobauble.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"death_mark": {
		name: "Death Mark",
		description: [
			"sta::Enemies with ",
			"yel::4 ",
			"sta::or more debuffs are ",
			"yel::marked for death",
			"sta::, increasing damage taken by ",
			"yel::50% ",
			"sta::from all sources for ",
			"blu::7 ",
			"gra::(+7 per stack) ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/34/Death_Mark.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"fuel_cell": {
		name: "Fuel Cell",
		description: [
			"sta::Hold an ",
			"blu::additional equipment charge ",
			"gra::(+1 per stack)",
			"sta::. ",
			"blu::Reduce equipment cooldown ",
			"sta::by ",
			"blu::15% ",
			"gra::(+15% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/4/4d/Fuel_Cell.png",
		rarity: ItemRarities.GREEN,
		challenge: "Pick up 5 different types of Equipment.",
		scaling: "Linear Exponential",
	},
	"ghors_tome": {
		name: "Ghor's Tome",
		description: [
			"blu::4% ",
			"gra::(+4% per stack) ",
			"sta::chance on kill to drop a treasure worth ",
			"blu::25$",
			"sta::. ",
			"blu::Scales over time",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/9/9a/Ghor%27s_Tome.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"harvesters_scythe": {
		name: "Harvester's Scythe",
		description: [
			"sta::Gain ",
			"yel::5% critical chance",
			"sta::. ",
			"yel::Critical strikes ",
			"gre::heal ",
			"sta::for ",
			"gre::8 ",
			"gra::(+4 per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e1/Harvester%27s_Scythe.png",
		rarity: ItemRarities.GREEN,
		challenge: "Complete a Prismatic Trial.",
		scaling: "Linear None",
	},
	"hopoo_feather": {
		name: "Hopoo Feather",
		description: [
			"sta::Gain ",
			"blu::+1 ",
			"gra::(+1 per stack) ",
			"sta::maximum ",
			"blu::jump count",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/3a/Hopoo_Feather.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"infusion": {
		name: "Infusion",
		description: [
			"sta::Killing an enemy increases your ",
			"gre::health permanently ",
			"sta::by ",
			"gre::1 ",
			"gra::(+1 per stack)",
			"sta::, up to a ",
			"gre::maximum ",
			"sta::of ",
			"gre::100 ",
			"gra::(+100 per stack) ",
			"gre::health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/7d/Infusion.png",
		rarity: ItemRarities.GREEN,
		challenge: "Defeat 3000 enemies.",
		scaling: "Linear",
	},
	"kjaros_band": {
		name: "Kjaro's Band",
		description: [
			"sta::Hits that deal ",
			"yel::more than 400% damage ",
			"sta::also blasts enemies with a ",
			"yel::runic flame tornado",
			"sta::, dealing ",
			"yel::300% ",
			"gra::(+300% per stack) ",
			"sta::TOTAL damage over time. Recharges every ",
			"blu::10 ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/eb/Kjaro%27s_Band.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"leeching_seed": {
		name: "Leeching Seed",
		description: [
			"sta::Dealing damage ",
			"gre::heals ",
			"sta::you for ",
			"gre::1 ",
			"gra::(+1 per stack) ",
			"gre::health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/a/a0/Leeching_Seed.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"lepton_daisy": {
		name: "Lepton Daisy",
		description: [
			"sta::Release a ",
			"gre::healing nova ",
			"sta::during the Teleporter event, ",
			"gre::healing ",
			"sta::all nearby allies for ",
			"gre::50% ",
			"sta::of their maximum health. Occurs ",
			"gre::1 ",
			"gra::(+1 per stack) ",
			"sta::times",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/73/Lepton_Daisy.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"old_guillotine": {
		name: "Old Guillotine",
		description: [
			"sta::Instantly kill Elite monsters below ",
			"red::13% ",
			"gra::(+13% per stack) ",
			"red::health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/8/8d/Old_Guillotine.png",
		rarity: ItemRarities.GREEN,
		challenge: "Defeat 500 elite monsters.",
		scaling: "Hyperbolic",
	},
	"old_war_stealthkit": {
		name: "Old War Stealthkit",
		description: [
			"sta::Falling below ",
			"red::25% health ",
			"sta::causes you to gain ",
			"blu::40% movement speed ",
			"sta::and ",
			"blu::invisibility ",
			"sta::for ",
			"blu::5s",
			"sta::. Recharges every ",
			"blu::30 seconds ",
			"gra::(-50% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/2c/Old_War_Stealthkit.png",
		rarity: ItemRarities.GREEN,
		scaling: "Exponential",
	},
	"predatory_instincts": {
		name: "Predatory Instincts",
		description: [
			"sta::Gain ",
			"yel::5% critical chance",
			"sta::. ",
			"yel::Critical strikes ",
			"sta::increase ",
			"yel::attack speed ",
			"sta::by ",
			"yel::12%",
			"sta::. Maximum cap of ",
			"yel::36% ",
			"gra::(+24% per stack) ",
			"yel::attack speed",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/39/Predatory_Instincts.png",
		rarity: ItemRarities.GREEN,
		challenge: "Reach +200% attack speed.",
		scaling: "Linear None",
	},
	"razorwire": {
		name: "Razorwire",
		description: [
			"sta::Getting hit causes you to explode in a burst of razors, dealing ",
			"yel::160% damage",
			"sta::. Hits up to ",
			"yel::5 ",
			"gra::(+2 per stack) ",
			"sta::targets in a ",
			"yel::25m ",
			"gra::(+10m per stack) ",
			"sta::radius",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/a/ac/Razorwire.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
		proc_coefficient: "0.5",
	},
	"red_whip": {
		name: "Red Whip",
		description: [
			"sta::Leaving combat boosts your ",
			"blu::movement speed ",
			"sta::by ",
			"blu::30% ",
			"gra::(+30% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/2a/Red_Whip.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"rose_buckler": {
		name: "Rose Buckler",
		description: [
			"gre::Increase armor ",
			"sta::by ",
			"gre::30 ",
			"gra::(+30 per stack) ",
			"blu::while sprinting",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/2f/Rose_Buckler.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
	},
	"runalds_band": {
		name: "Runald's Band",
		description: [
			"sta::Hits that deal ",
			"yel::more than 400% damage ",
			"sta::also blasts enemies with a ",
			"yel::runic ice blast",
			"sta::, ",
			"blu::slowing them ",
			"sta::by ",
			"blu::80% ",
			"sta::for ",
			"blu::3s ",
			"gra::(+3s per stack) ",
			"sta::and dealing ",
			"yel::250% ",
			"gra::(+250% per stack) ",
			"sta::TOTAL damage. Recharges every ",
			"blu::10 ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/05/Runald%27s_Band.png",
		rarity: ItemRarities.GREEN,
		challenge: "Discover the hidden chamber in the Abandoned Aqueduct.",
		scaling: "Linear",
	},
	"squid_polyp": {
		name: "Squid Polyp",
		description: [
			"sta::Activating an interactable summons a ",
			"yel::Squid Turret ",
			"sta::that attacks nearby enemies at ",
			"yel::100% ",
			"gra::(+100% per stack) ",
			"yel::attack speed",
			"sta::. Lasts ",
			"blu::30 ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/de/Squid_Polyp.png",
		rarity: ItemRarities.GREEN,
		challenge: "Activate 6 turrets in a single run.",
		scaling: "Linear",
	},
	"ukelele": {
		name: "Ukelele",
		description: [
			"yel::25% ",
			"sta::chance to fire ",
			"yel::chain lightning ",
			"sta::for ",
			"yel::80% ",
			"sta::TOTAL damage on up to ",
			"yel::3 ",
			"gra::(+2 per stack) ",
			"sta::targets within ",
			"yel::20m ",
			"gra::(+2m per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/9/98/Ukulele.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
		proc_coefficient: "0.2",
	},
	"war_horn": {
		name: "War Horn",
		description: [
			"sta::Activating your Equipment gives you ",
			"yel::+70% attack speed ",
			"sta::for ",
			"yel::8s ",
			"gra::(+4s per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/9/9c/War_Horn.png",
		rarity: ItemRarities.GREEN,
		challenge: "Complete 3 Combat Shrines in a single stage.",
		scaling: "Linear",
	},
	"wax_quail": {
		name: "Wax Quail",
		description: [
			"blu::Jumping ",
			"sta::while ",
			"blu::sprinting ",
			"sta::boosts you forward by ",
			"blu::10m ",
			"gra::(+10m per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/6c/Wax_Quail.png",
		rarity: ItemRarities.GREEN,
		challenge: "Reach +300% movespeed (includes sprinting).",
		scaling: "Linear",
	},
	"will_o_the_wisp": {
		name: "Will-o'-the-wisp",
		description: [
			"sta::On killing an enemy, spawn a ",
			"yel::lava pillar ",
			"sta::in a ",
			"yel::12m ",
			"gra::(+2.4m per stack) ",
			"sta::radius for ",
			"yel::350% ",
			"gra::(+280% per stack) ",
			"sta::base damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c4/Will-o%27-the-wisp.png",
		rarity: ItemRarities.GREEN,
		scaling: "Linear",
		proc_coefficient: "1",
	},
	"item_scrap_green": {
		name: "Item Scrap, Green",
		description: [
			"sta::Does nothing. Prioritized when used with 3D Printers",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/0/01/Item_Scrap%2C_Green.png",
		rarity: ItemRarities.GREEN,
	},
	"57_leaf_clover": {
		name: "57 Leaf Clover",
		description: [
			"sta::All random effects are rolled ",
			"blu::+1 ",
			"gra::(+1 per stack) ",
			"sta::times for a ",
			"blu::favorable outcome",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e5/57_Leaf_Clover.png",
		rarity: ItemRarities.RED,
		challenge: "Complete 20 stages in a single run.",
		scaling: "Linear",
	},
	"aegis": {
		name: "Aegis",
		description: [
			"sta::Healing past full grants you a ",
			"gre::temporary barrier ",
			"sta::for ",
			"gre::50% ",
			"gra::(+50% per stack) ",
			"sta::of the amount you ",
			"gre::healed",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e5/Aegis.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"alien_head": {
		name: "Alien Head",
		description: [
			"blu::Reduce skill cooldowns ",
			"sta::by ",
			"blu::25% ",
			"gra::(+25% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/25/Alien_Head.png",
		rarity: ItemRarities.RED,
		scaling: "Exponential",
	},
	"brainstalks": {
		name: "Brainstalks",
		description: [
			"sta::Upon killing an elite monster, ",
			"yel::enter a frenzy ",
			"sta::for ",
			"yel::4s ",
			"gra::(+4s per stack) ",
			"sta::where ",
			"blu::skills have 0.5s cooldowns",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c0/Brainstalks.png",
		rarity: ItemRarities.RED,
		challenge: "Defeat an Elite boss on Monsoon difficulty.",
		scaling: "Linear",
	},
	"brilliant_behemoth": {
		name: "Brilliant Behemoth",
		description: [
			"sta::All your ",
			"yel::attacks explode ",
			"sta::in a ",
			"yel::4m ",
			"gra::(+2.5m per stack) ",
			"sta::radius for a bonus ",
			"yel::60% ",
			"sta::TOTAL damage to nearby enemies",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/fa/Brilliant_Behemoth.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"ceremonial_dagger": {
		name: "Ceremonial Dagger",
		description: [
			"sta::Killing an enemy fires out ",
			"yel::3 homing daggers ",
			"sta::that deal ",
			"yel::150% ",
			"gra::(+150% per stack) ",
			"sta::base damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/76/Ceremonial_Dagger.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
		proc_coefficient: "1",
	},
	"defensive_microbots": {
		name: "Defensive Microbots",
		description: [
			"sta::Shoot down ",
			"yel::1 ",
			"gra::(+1 per stack) ",
			"sta::projectiles within ",
			"yel::20m ",
			"sta::every ",
			"yel::0.5 seconds",
			"sta::. ",
			"blu::Recharge rate scales with attack speed",	
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/dd/Defensive_Microbots.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"dios_best_friend": {
		name: "Dio's Best Friend",
		description: [
			"blu::Upon death",
			"sta::, this item will be ",
			"blu::consumed ",
			"sta::and you will ",
			"gre::return to life ",
			"sta::with ",
			"gre::3 seconds of invulnerability",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/dc/Dio%27s_Best_Friend.png",
		rarity: ItemRarities.RED,
		challenge: "Stay alive for 30 consecutive minutes.",
		scaling: "Linear",
	},
	"frost_relic": {
		name: "Frost Relic",
		description: [
			"sta::Killing an enemy surrounds you with an ",
			"yel::ice storm ",
			"sta::that deals ",
			"yel::1200% damage per second ",
			"sta::and ",
			"blu::slows ",
			"sta::enemies by ",
			"blu::80% ",
			"sta::for ",
			"blu::1.5s",
			"sta::. The storm ",
			"yel::grows with every kill",
			"sta::, increasing its radius by ",
			"yel::2m",
			"sta::. Stacks up to ",
			"yel::18m ",
			"gra::(+12m per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/5/58/Frost_Relic.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
		proc_coefficient: "0.2",
	},
	"head_st": {
		name: "H3AD-5T v2",
		description: [
			"sta::Increase ",
			"blu::jump height",
			"sta::. Creates a ",
			"yel::5m-100m ",
			"sta::radius ",
			"yel::kinetic explosion ",
			"sta::on hitting the ground, dealing ",
			"yel::1000%-10000% ",
			"sta::base damage that scales up with ",
			"yel::fall distance",
			"sta::. Recharges in ",
			"yel::10 ",
			"gra::(-50% per stack) ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/36/H3AD-5T_v2.png",
		rarity: ItemRarities.RED,
		scaling: "Exponential",
	},
	"happiest_mask": {
		name: "Happiest Mask",
		description: [
			"sta::Killing enemies has a ",
			"yel::7% ",
			"sta::chance to ",
			"yel::spawn a ghost ",
			"sta::of the killed enemy with ",
			"yel::1500% ",
			"sta::damage. Lasts ",
			"yel::30s ",
			"gra::(+30s per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/d4/Happiest_Mask.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"hardlight_afterburner": {
		name: "Hardlight Afterburner",
		description: [
			"sta::Add ",
			"blu::+2 ",
			"gra::(+2 per stack) ",
			"sta::charges of your ",
			"blu::Utility skill",
			"sta::. ",
			"blu::Reduces Utility skill cooldown ",
			"sta::by ",
			"blu::33%",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/20/Hardlight_Afterburner.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"interstellar_desk_plant": {
		name: "Interstellar Desk Plant",
		description: [
			"sta::On kill, plant a ",
			"gre::healing ",
			"sta::fruit seed that grows into a plant after ",
			"blu::5 ",
			"sta::seconds. The plant ",
			"gre::heals ",
			"sta::for ",
			"gre::10% ",
			"sta::of ",
			"gre::maximum health ",
			"sta::every 0.5 second to all allies within ",
			"gre::5m ",
			"gra::(+5.0m per stack)",
			"sta::. Lasts ",
			"blu::10 ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/1/1e/Interstellar_Desk_Plant.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"nkuhanas_opinion": {
		name: "N'kuhana's Opinion",
		description: [
			"sta::Store ",
			"gre::100% ",
			"gra::(+100% per stack) ",
			"sta::of ",
			"sta::healing as ",
			"gre::Soul Energy",
			"sta::. After your ",
			"gre::Soul Energy ",
			"sta::reaches ",
			"gre::10% ",
			"sta::of your ",
			"gre::maximum health",
			"sta::, ",
			"yel::fire a skull ",
			"sta::that deals ",
			"yel::250% ",
			"sta::of your ",
			"gre::Soul Energy ",
			"sta::as ",
			"yel::damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c9/N%27kuhana%27s_Opinion.png",
		rarity: ItemRarities.RED,
		challenge: "Find the Altar to N'kuhana.",
		scaling: "Linear",
		proc_coefficient: "0.2",
	},
	"rejuv_rack": {
		name: "Rejuvenation Rack",
		description: [
			"gre::Heal +100% ",
			"gra::(+100% per stack) ",
			"sta::more",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/0a/Rejuvenation_Rack.png",
		rarity: ItemRarities.RED,
		challenge: "Without healing, reach and complete the 3rd Teleporter event.",
		scaling: "Linear",
	},
	"resonance_disc": {
		name: "Resonance Disc",
		description: [
			"sta::Killing ",
			"yel::4 ",
			"sta::enemies in ",
			"blu::7 seconds ",
			"sta::charges the Resonance Disc. The disc launches itself toward a target for ",
			"yel::300% ",
			"sta::base damage ",
			"gra::(+300% per stack)",
			"sta::, piercing all enemies it doesn't kill, and then explodes for ",
			"yel::1000% ",
			"sta::base damage ",
			"gra::(+1000% per stack)",
			"sta::. Returns to the user, striking all enemies along the way for ",
			"yel::300% ",
			"sta::base damage ",
			"gra::(+300% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/8/8d/Resonance_Disc.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
		proc_coefficient: "Launch and Return: 1, Explosion: 0",
	},
	"sentient_meat_hook": {
		name: "Sentient Meat Hook",
		description: [
			"yel::20% ",
			"gra::(+20% per stack) ",
			"sta::chance on hit to ",
			"yel::fire homing hooks ",
			"sta::at up to ",
			"yel::10 ",
			"gra::(+5 per stack) ",
			"sta::enemies for ",
			"yel::100%", 
			"sta::TOTAL damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e7/Sentient_Meat_Hook.png",
		rarity: ItemRarities.RED,
		challenge: "Loop back to the first stage.",
		scaling: "Hyperbolic Linear",
		proc_coefficient: "0.33",
	},
	"shattering_justice": {
		name: "Shattering Justice",
		description: [
			"sta::After hitting an enemy ",
			"yel::5 ",
			"sta::times, reduce their ",
			"yel::armor ",
			"sta::by ",
			"yel::60 ",
			"sta::for ",
			"yel::8 ",
			"gra::(+8 per stack) ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/2d/Shattering_Justice.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"soulbound_catalyst": {
		name: "Soulbound Catalyst",
		description: [
			"yel::Kills reduce ",
			"blu::equipment cooldown ",
			"sta::by ",
			"blu::4s ",
			"gra::(+2s per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/f1/Soulbound_Catalyst.png",
		rarity: ItemRarities.RED,
		challenge: "Discover and activate 8 unique Newt Altars.",
		scaling: "Linear",
	},
	"tesla_coil": {
		name: "Unstable Tesla Coil",
		description: [
			"sta::Fire out ",
			"yel::lightning ",
			"sta::that hits ",
			"yel::3 ",
			"gra::(+2 per stack) enemies for ",
			"yel::200% ",
			"sta::base damage every ",
			"yel::0.5s",
			"sta::. The Tesla Coil switches off every ",
			"yel::10 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e4/Unstable_Tesla_Coil.png",
		rarity: ItemRarities.RED,
		challenge: "Deal 5000 damage in one shot.",
		scaling: "Linear",
		proc_coefficient: "0.3",
	},
	"wake_of_vultures": {
		name: "Wake of Vultures",
		description: [
			"sta::Gain the ",
			"yel::power ",
			"sta::of any killed elite monster for ",
			"yel::8s ",
			"gra::(+5s per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/f8/Wake_of_Vultures.png",
		rarity: ItemRarities.RED,
		scaling: "Linear",
	},
	"item_scrap_red": {
		name: "Item Scrap, Red",
		description: [
			"sta::Does nothing. Prioritized when used with 3D Printers",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/4/48/Item_Scrap%2C_Red.png",
		rarity: ItemRarities.RED,
	},
	"artifact_key": {
		name: "Artifact Key",
		description: [
			"sta::A stone shard with immense power. ",
			"br::",
			"gra::Used in Bulwark's Ambry to unlock Artifacts",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/1/17/Artifact_Key.png",
		rarity: ItemRarities.YELLOW,
	},
	"charged_perforator": {
		name: "Charged Perforator",
		description: [
			"yel::10% ",
			"sta::chance on hit to down a lightning strike, dealing ",
			"yel::500% ",
			"gra::(+500% per stack) ",
			"sta::damage",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/c/cc/Charged_Perforator.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
		proc_coefficient: "1",
	},
	"empathy_cores": {
		name: "Empathy Cores",
		description: [
			"sta::Every 30 seconds, ",
			"blu::summon two Solus Probes ",
			"sta::that gain ",
			"yel::+100% ",
			"gra::(+100% per stack) ",
			"sta::damage per ",
			"blu::ally on your team",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/5/51/Empathy_Cores.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"genesis_loop": {
		name: "Genesis Loop",
		description: [
			"sta::Falling below ",
			"red::25% health ",
			"sta::causes you to explode, dealing ",
			"yel::6000% base damage",
			"sta::. Recharges every ",
			"blu::30 / (2 ",
			"gra::+1 per stack",
			"blu::) seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c8/Genesis_Loop.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
		proc_coefficient: "1",
	},
	"halcyon_seed": {
		name: "Halcyon Seed",
		description: [
			"sta::Summon",
			"yel::Aurelionite",
			"sta::during the teleporter event. It has ",
			"yel::100% ",
			"gra::(+50% per stack) ",
			"yel::damage ",
			"sta::and ",
			"gre::100% ",
			"gra::(+100% per stack) ",
			"gre::health", 
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e6/Halcyon_Seed.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"irradiant_pearl": {
		name: "Irradiant Pearl",
		description: [
			"sta::Increases ",
			"blu::ALL stats ",
			"sta::by ",
			"blu::10% ",
			"gra::(+10% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/ef/Irradiant_Pearl.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"little_disciple": {
		name: "Little Disciple",
		description: [
			"sta::Fire a ",
			"yel::tracking wisp ",
			"sta::for ",
			"yel::300% ",
			"gra::(+300% per stack) ",
			"yel::damage",
			"sta::. Fires every ",
			"blu::1.6 ",
			"sta::seconds while sprinting. Fire rate increases with ",
			"blu::movement speed",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/08/Little_Disciple.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
		proc_coefficient: "1",
	},
	"mired_urn": {
		name: "Mired Urn",
		description: [
			"sta::While in combat, the nearest 1 ",
			"gra::(+1 per stack) ",
			"sta::enemies to you within ",
			"yel::13m ",
			"sta::will be 'tethered' to you, dealing ",
			"yel::100% ",
			"sta::damage per second, applying ",
			"yel::tar",
			"sta::, and ",
			"gre::healing ",
			"sta::you for ",
			"gre::100% ",
			"sta::of the damage dealt",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/62/Mired_Urn.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"molten_perforator": {
		name: "Molten Perforator",
		description: [
			"yel::10% ",
			"sta::chance on hit to call forth ",
			"yel::3 magma balls ",
			"sta::from an enemy, dealing ",
			"yel::300% ",
			"gra::(+300% per stack) ",
			"sta::damage each",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/71/Molten_Perforator.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
		proc_coefficient: "3 x 0.7"
	},
	"pearl": {
		name: "Pearl",
		description: [
			"sta::Increases ",
			"gre::maximum health ",
			"sta::by ",
			"gre::10% ",
			"gra::(+10% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/73/Pearl.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"planula": {
		name: "Planula",
		description: [
			"sta::Heal from ",
			"yel::incoming damage ",
			"sta::for ",
			"gre::15 ",
			"gra::(+15 per stack)",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/a/a9/Planula.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"queens_gland": {
		name: "Queen's Gland",
		description: [
			"sta::Every 30 seconds, ",
			"blu::summon a Beetle Guard ",
			"sta::with bonus ",
			"gre::300% ",
			"sta::damage and ",
			"gre::100% health",
			"sta::. Can have up to ",
			"blu::1 ",
			"gra::(+1 per stack) ",
			"sta::Guards at a time",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/0b/Queen%27s_Gland.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"shatterspleen": {
		name: "Shatterspleen",
		description: [
			"sta::Gain ",
			"yel::5% critical chance",
			"sta::. ",
			"yel::Critical Strikes bleed ",
			"sta::enemies ",
			"sta::for ",
			"yel::240% ",
			"sta::base damage. ",
			"yel::Bleeding ",
			"sta::enemies ",
			"yel::explode ",
			"sta::on death for ",
			"yel::400% ",
			"gra::(+400% per stack) ",
			"sta::damage, plus an additional ",
			"yel::15% ",
			"gra::(+15% per stack) ",
			"sta::of their maximum health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/cd/Shatterspleen.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear None",
	},
	"titanic_knurl": {
		name: "Titanic Knurl",
		description: [
			"gre::Increase maximum health ",
			"sta::by ",
			"gre::40 ",
			"gra::(+40 per stack) ",
			"sta::and ",
			"gre::base health regeneration ",
			"sta::by ",
			"gre::+1.6 hp/s ",
			"gra::(+1.6 hp/s per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/9/9f/Titanic_Knurl.png",
		rarity: ItemRarities.YELLOW,
		scaling: "Linear",
	},
	"item_scrap_yellow": {
		name: "Item Scrap, Yellow",
		description: [
			"sta::Does nothing. Prioritized when used with 3D Printers",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/7/7f/Item_Scrap%2C_Yellow.png",
		rarity: ItemRarities.YELLOW,
	},
	"beads_of_fealty": {
		name: "Beads of Fealty",
		description: [
			"sta::Seems to do nothing...",
			"red::but...",
			"br::",
			"gra::Obliterating at the Obelisk will instead transport players to A Moment, Whole where one of four Twisted Scavengers can be found"
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/07/Beads_of_Fealty.png",
		rarity: ItemRarities.BLUE,
	},
	"brittle_crown": {
		name: "Brittle Crown",
		description: [
			"blu::30% chance on hit ",
			"sta::to gain ",
			"blu::2 ",
			"gra::(+2 per stack) ",
			"blu::gold",
			"sta::. ",
			"blu::Scales over time",
			"sta::. ",
			"red::Lose gold ",
			"sta::on taking damage equal to ",
			"red::100% ",
			"gra::(+100% per stack) ",
			"sta::of the ",
			"red::maximum health percentage you lost",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/a/ae/Brittle_Crown.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear",
	},
	"corpsebloom": {
		name: "Corpsebloom",
		description: [
			"gre::Heal +100% ",
			"gra::(+100% per stack) ",
			"sta::more. ",
			"gra::All healing is applied over time",
			"sta::. Can ",
			"gre::heal ",
			"sta::for a ",
			"gre::maximum ",
			"sta::of ",
			"gre::10% ",
			"gra::(-50% per stack) ",
			"sta::of your ",
			"gre::health per second",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/31/Corpsebloom.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear Hyperbolic",
	},
	"defiant_gouge": {
		name: "Defiant Gouge",
		description: [
			"sta::Using a Shrine summons ",
			"red::enemies ",
			"gra::(stronger per stack) ",
			"sta::nearby. ",
			"blu::Scales over time",
			"sta::.",
			"br::",
			"gra::Starts at 40% difficulty. Each stack adds 40% more difficulty"
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/b/b5/Defiant_Gouge.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear",
	},
	"essence_of_heresy": {
		name: "Essence of Heresy",
		description: [
			"blu::Replace your Special Skill with Ruin. ",
			"br::",
			"sta::Dealing damage adds a stack of ",
			"yel::Ruin ",
			"sta::for 10 ",
			"gra::(+10 per stack) ",
			"sta::seconds. Activating the skill ",
			"yel::detonates ",
			"sta::all Ruin stacks at unlimited range, dealing ",
			"yel::300% damage ",
			"sta::plus ",
			"yel::120% damage per stack of Ruin",
			"sta::. Recharges after 8 ",
			"gra::(+8 per stack) ",
			"sta::seconds",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/3/3e/Essence_of_Heresy.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear",
	},
	"focused_convergence": {
		name: "Focused Convergence",
		description: [
			"sta::Teleporters charge ",
			"blu::30% ",
			"gra::(+30% per stack) ",
			"blu::faster",
			"sta::, but the size of the Teleporter zone is ",
			"red::50% ",
			"gra::(-50% per stack) ",
			"sta::smaller",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/2c/Focused_Convergence.png",
		rarity: ItemRarities.BLUE,
		challenge: "In 4 consecutive stages don't leave the Teleporter radius until it's fully charged.",
		scaling: "Linear Hyperbolic",
	},
	"gesture_of_the_drowned": {
		name: "Gesture of the Drowned",
		description: [
			"blu::Reduce Equipment cooldowns ",
			"sta::by ",
			"blu::50% ",
			"gra::(+15% per stack)",
			"sta::. Forces your Equipment to ",
			"blu::activate ",
			"sta::whenever it is off ",
			"blu::cooldown",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/c9/Gesture_of_the_Drowned.png",
		rarity: ItemRarities.BLUE,
		challenge: "Kill 20 Hermit Crabs by chasing them off the edge of the map.",
		scaling: "Exponential",
	},
	"hooks_of_heresy": {
		name: "Hooks of Heresy",
		description: [
			"blu::Replace your Secondary Skill ",
			"sta::with ",
			"blu::Slicing Maelstrom",
			"sta::. ",
			"br::",
			"sta::Charge up a projectile that deals ",
			"yel::875% damage per second ",
			"sta::to nearby enemies, exploding after ",
			"blu::3 ",
			"sta::seconds to deal ",
			"yel::700% damage ",
			"sta::and ",
			"yel::root ",
			"sta::enemies for ",
			"blu::3 ",
			"gra::(+3 per stack) ",
			"sta::seconds. Recharges after 5 ",
			"gra::(+5 per stack) ",
			"sta::seconds",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/6/66/Hooks_of_Heresy.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear",
	},
	"mercurial_rachis": {
		name: "Mercurial Rachis",
		description: [
			"sta::Creates a Ward of Power in a random location nearby that buffs both enemies and allies within ",
			"blu::16m ",
			"gra::(+50% per stack)",
			"sta::, causing them to deal ",
			"yel::+50% ",
			"sta::damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/25/Mercurial_Rachis.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear",
	},
	"purity": {
		name: "Purity",
		description: [
			"sta::All skill cooldowns are reduced by ",
			"blu::2 ",
			"gra::(+1 per stack) ",
			"sta::seconds. All random effects are rolled ",
			"blu::+1 ",
			"gra::(+1 per stack) ",
			"sta::times for an ",
			"red::unfavorable outcome",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/a/a2/Purity.png",
		rarity: ItemRarities.BLUE,
		challenge: "Beat the game on Monsoon difficulty.",
		scaling: "Linear",
	},
	"shaped_glass": {
		name: "Shaped Glass",
		description: [
			"sta::Increase base damage by ",
			"yel::100% ",
			"gra::(+100% per stack)",
			"sta::. ",
			"gre::Reduce maximum health by 50% ",
			"gra::(+50% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/ff/Shaped_Glass.png",
		rarity: ItemRarities.BLUE,
		scaling: "Exponential",
	},
	"strides_of_heresy": {
		name: "Strides of Heresy",
		description: [
			"blu::Replace your Utility Skill ",
			"sta::with ",
			"blu::Shadowfade",
			"sta::. ",
			"br::",
			"sta::Fade away, becoming ",
			"blu::intangible ",
			"sta::and gaining ",
			"blu::+30% movement speed",
			"sta::. ",
			"gre::Heal ",
			"sta::for ",
			"gre::18.2% ",
			"gra::(+18.2% per stack) ",
			"gre::of your maximum health",
			"sta::. Lasts 3 ",
			"gra::(+3 per stack) ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/1/1a/Strides_of_Heresy.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear",
	},
	"transcendence": {
		name: "Transcendence",
		description: [
			"gre::Convert ",
			"sta::all but ",
			"gre::1 health ",
			"sta::into ",
			"gre::regenerating shields",
			"sta::. ",
			"gre::Gain 50% ",
			"gra::(+25% per stack) ",
			"gre::maximum health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/8/85/Transcendence.png",
		rarity: ItemRarities.BLUE,
		scaling: "Linear",
	},
	"visions_of_heresy": {
		name: "Visions of Heresy",
		description: [
			"blu::Replace your Primary Skill ",
			"sta::with ",
			"blu::Hungering Gaze",
			"sta::. ",
			"br::",
			"sta::Fire a flurry of ",
			"blu::tracking shards ",
			"sta::that detonate after a delay, dealing ",
			"yel::120% ",
			"sta::base damage. Hold up to 12 charges ",
			"gra::(+12 per stack) ",
			"sta::that reload after 2 seconds ",
			"gra::(+2 per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/31/Visions_of_Heresy.png",
		rarity: ItemRarities.BLUE,
		challenge: "Kill 15 boss monsters in a single run.",
		scaling: "Linear",
		proc_coefficient: "Initial hit: 0.1, Explosion: 1",
	},
	"effigy_of_grief": {
		name: "Effigy of Grief",
		description: [
			"sta::ALL characters within are ",
			"blu::slowed by 50% ",
			"sta::and have their ",
			"yel::armor reduced by 20",
			"sta::. Can place up to ",
			"blu::5",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/4/45/Effigy_of_Grief.png",
		rarity: ItemRarities.BLUE,
		cooldown: 15,
	},
	"glowing_meteorite": {
		name: "Glowing Meteorite",
		description: [
			"yel::Rain meteors ",
			"sta::from the sky, damaging ALL characters for ",
			"yel::600% damage per blast",
			"sta::. Lasts 20 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/f4/Glowing_Meteorite.png",
		rarity: ItemRarities.BLUE,
		challenge: "Carry 5 Lunar Items in a single run.",
		cooldown: 140,
		proc_coefficient: "1",
	},
	"helfire_tincture": {
		name: "Helfire Tincture",
		description: [
			"sta::Ignite ALL characters within 15m for 12s. Deal ",
			"yel::5% of your maximum health/second as burning ",
			"sta::to yourself. The burn is ",
			"yel::0.5x ",
			"sta::stronger on allies, and ",
			"yel::24x ",
			"sta::stronger on enemies",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/4/4d/Helfire_Tincture.png",
		rarity: ItemRarities.BLUE,
		challenge: "Kill 15 enemies simultaneously.",
		cooldown: 45,
	},
	"spinel_tonic": {
		name: "Spinel Tonic",
		description: [
			"sta::Drink the Tonic, gaining a boost for 20 seconds. Increases ",
			"yel::damage ",
			"sta::by ",
			"yel::+100%",
			"sta::. Increases ",
			"yel::attack speed ",
			"sta::by ",
			"yel::+70%",
			"sta::. Increases ",
			"yel::armor ",
			"sta::by ",
			"yel::+20",
			"sta::. Increases ",
			"gre::maximum health ",
			"sta::by ",
			"gre::+50%",
			"sta::. Increases ",
			"gre::passive health regeneration ",
			"sta::by ",
			"gre::+300%",
			"sta::. Increases ",
			"blu::movespeed ",
			"sta::by ",
			"blu::+30%",
			"sta::.",
			"br::",
			"sta::When the Tonic wears off, you have a ",
			"red::20% ",
			"sta::chance to gain a ",
			"red::Tonic Affliction, reducing all of your stats ",
			"sta:by ",
			"red::-5% ",
			"gra::(-5% per stack)",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/29/Spinel_Tonic.png",
		rarity: ItemRarities.BLUE,
		challenge: "Discover and enter three unique portals.",
		cooldown: 60.
	},
	"blast_shower": {
		name: "Blast Shower",
		description: [
			"blu::Cleanse ",
			"sta::all negative effects. Includes debuffs, damage over time, and nearby projectiles",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/4/4f/Blast_Shower.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Die three times while burning.",
		cooldown: 20,
	},
	"disposable_missile_launcher": {
		name: "Disposable Missile Launcher",
		description: [
			"sta::Fire a swarm of ",
			"yel::12 ",
			"sta::missiles that deal ",
			"yel::12x300% damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/78/Disposable_Missile_Launcher.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 45,
		proc_coefficient: "1",
	},
	"eccentric_vase": {
		name: "Eccentric Vase",
		description: [
			"sta::Create a ",
			"blu::quantum tunnel ",
			"sta::of up to ",
			"blu::1000m ",
			"sta::in length. Lasts 30 seconds.",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/c/ce/Eccentric_Vase.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Defeat the unique guardians of Gilded Coast without any beacons deactivating.",
		cooldown: 45,
	},
	"foreign_fruit": {
		name: "Foreign Fruit",
		description: [
			"sta::Instantly heal for ",
			"gre::50% of your maximum health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/d0/Foreign_Fruit.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 45,
	},
	"forgive_me_please": {
		name: "Forgive Me Please",
		description: [
			"sta::Throw a cursed doll out that ",
			"yel::triggers ",
			"sta::any ",
			"yel::On-Kill ",
			"sta::effects you have every ",
			"blu::1 ",
			"sta::second for ",
			"blu::8 ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/78/Forgive_Me_Please.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Die 20 times",
		cooldown: 45,
	},
	"fuel_array": {
		name: "Fuel Array",
		description: [
			"sta::Looks like it could power something. ",
			"red::EXTREMELY unstable...",
			"br::",
			"gra::A 30m explosion is triggered upon dropping below 50% of maximum health, dealing 300% of holder's maximum health to holder and enemies in radius.",
			"br::",
			"gra::Completes the Power Plant challenge if brought to the broken robot in Abyssal Depths, unlocking REX as a survivor",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/fe/Fuel_Array.png",
		rarity: ItemRarities.EQUIPMENT,
	},
	"gnarled_woodsprite": {
		name: "Gnarled Woodsprite",
		description: [
			"sta::Gain a Woodsprite follower that heals for ",
			"gre::1.5% of your maximum health/second",
			"sta::. Can be sent to an ally to heal them for ",
			"gre::10% of their maximum health",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/d8/Gnarled_Woodsprite.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Fully upgrade a Shrine of the Woods.",
		cooldown: 15,
	},
	"gorags_opus": {
		name: "Gorag's Opus",
		description: [
			"sta::All allies enter a ",
			"yel::frenzy ",
			"sta::for ",
			"blu::7 ",
			"sta::seconds. Increases ",
			"blu::movement speed ",
			"sta::by ",
			"blu::50% ",
			"sta::and ",
			"yel::attack speed ",
			"sta::by ",
			"yel::100%",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/5/56/Gorag%27s_Opus.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 45,
	},
	"jade_elephant": {
		name: "Jade Elephant",
		description: [
			"sta::Gain ",
			"yel::500 armor ",
			"sta::for ",
			"blu::5 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/4/41/Jade_Elephant.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 45,
	},
	"milky_chrysalis": {
		name: "Milky Chrysalis",
		description: [
			"sta::Sprout wings and ",
			"blu::fly for 15 seconds",
			"sta::. Gain ",
			"blu::+20% movement speed ",
			"sta::for the duration",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/e3/Milky_Chrysalis.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 60,
	},
	"ocular_hud": {
		name: "Ocular HUD",
		description: [
			"sta::Gain ",
			"yel::+100% Critical Strike Chance ",
			"sta::for 8 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/68/Ocular_HUD.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 60,
	},
	"preon_accumulator": {
		name: "Preon Accumulator",
		description: [
			"sta::Fires preon tendrils, zapping enemies within 35m for up to ",
			"yel::600% damage/second",
			"sta::. On contact, detonate in an enormous 20m explosion for ",
			"yel::4000% damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/f/fe/Preon_Accumulator.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Open the Timed Security Chest on Rallypoint Delta",
		cooldown: 140,
		proc_coefficient: "Explosion: 1, Periodic Sparks: 0.1",
	},
	"primordial_cube": {
		name: "Primordial Cube",
		description: [
			"sta::Fire a black hole that ",
			"blu::draws enemies within 30m into its center",
			"sta::. Lasts 10 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/d9/Primordial_Cube.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 60,
	},
	"radar_scanner": {
		name: "Radar Scanner",
		description: [
			"blu::Reveal ",
			"sta::all interactables within 500m for ",
			"blu::10 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/7/7f/Radar_Scanner.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Collect 10 Monster or Environment Logs.",
		cooldown: 45,
	},
	"recycler": {
		name: "Recycler",
		description: [
			"blu::Transform ",
			"sta::an Item or Equipment into a different one. ",
			"blu::Can only be converted into the same tier one time",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/67/Recycler.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Destroy 20 flying rocks in Sky Meadow.",
		cooldown: 45,
	},
	"royal_capacitor": {
		name: "Royal Capacitor",
		description: [
			"sta::Call down a lightning strike on a targeted monster, dealing ",
			"yel::3000% damage ",
			"sta::and ",
			"yel::stunning ",
			"sta::nearby monsters",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/e/ef/Royal_Capacitor.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Defeat the Teleporter bosses after activating 2 Shrines of the Mountain.",
		cooldown: 20,
		proc_coefficient: "1",
	},
	"sawmerang": {
		name: "Sawmerang",
		description: [
			"sta::Throw ",
			"yel::three large saw blades ",
			"sta::that slice through enemies for ",
			"yel::3x400% ",
			"sta::damage. Also deals an additional ",
			"yel::3x100% damage per second ",
			"sta::while ",
			"yel::bleeding ",
			"sta::enemies. Can ",
			"yel::strike ",
			"sta::enemies again on the way back",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/62/Sawmerang.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 45,
		proc_coefficient: "Initial hit and hit on return: 1, While bleeding enemies: 0.2",
	},
	"super_massive_leech": {
		name: "Super Massive Leech",
		description: [
			"gre::Heal ",
			"sta::for ",
			"gre::20% ",
			"sta::of the ",
			"yel::damage ",
			"sta::you deal. Lasts ",
			"gre::8 ",
			"sta::seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/a/ae/Super_Massive_Leech.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 60,
	},
	"the_backup": {
		name: "The Back-up",
		description: [
			"sta::Call ",
			"yel::4 Strike Drones ",
			"sta::to fight for you. Lasts 25 seconds",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/3/39/The_Back-up.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Repair 30 drones or turrets.",
		cooldown: 100,
	},
	"the_crowdfunder": {
		name: "The Crowdfunder",
		description: [
			"sta::Fires a continuous barrage that deals ",
			"yel::100% damage per bullet",
			"sta::. Costs $1 per bullet. Cost increases over time",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/d4/The_Crowdfunder.png",
		rarity: ItemRarities.EQUIPMENT,
		challenge: "Collect $30,480 total gold.",
		proc_coefficient: "1",
	},
	"volcanic_egg": {
		name: "Volcanic Egg",
		description: [
			"sta::Turn into a ",
			"yel::draconic fireball ",
			"sta::for ",
			"yel::5 ",
			"sta::seconds. Deal ",
			"yel::500% damage ",
			"sta::on impact. Detonates at the end for ",
			"yel::800% damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/2/2e/Volcanic_Egg.png",
		rarity: ItemRarities.EQUIPMENT,
		cooldown: 30,
		proc_coefficient: "1",
	},
	"aspect_ice": {
		name: "Her Biting Embrace",
		description: [
			"sta::Become an aspect of ice. ",
			"br::",
			"gra::Always active.",
			"br::",
			"gra::Holder's attacks slow enemies by 80% for 1.5s. On death, holder explodes for 150% damage, freezing all enemies in the explosion radius",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/8/8b/Her_Biting_Embrace.png",
		rarity: ItemRarities.EQUIPMENT,
		proc_coefficient: "0.75",
	},
	"aspect_fire": {
		name: "Ifrit's Distinction",
		description: [
			"sta::Become an aspect of fire. ",
			"br::",
			"gra::Always active.",
			"br::",
			"gra::A trail of fire is left by the holder, apply a percent burn on hit to enemies",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/08/Ifrit%27s_Distinction.png",
		rarity: ItemRarities.EQUIPMENT,
	},
	"aspect_corruption": {
		name: "N'kuhana's Retort",
		description: [
			"sta::Become an aspect of corruption. ",
			"br::",
			"gra::Always active.",
			"br::",
			"gra::3-4 Urchins are occasionally launched out of the holder, dealing 100% damage and a healing disabled debuff for 8s",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/9/9b/N%27kuhana%27s_Retort.png",
		rarity: ItemRarities.EQUIPMENT,
		proc_coefficient: "1",
	},
	"aspect_perfection": {
		name: "Shared Design",
		description: [
			"sta::Become an aspect of perfection. ",
			"br::",
			"gra::Always active.",
			"br::",
			"gra::Holder's attacks cripple enemies on hit. Holder occasionally fire 5 bomb projectiles at enemies, gains 30% increased movement speed and gains 25% maximum health. Holder's health is replaced with shields",
		],
		image_url: "https://static.wikia.nocookie.net/riskofrain2_gamepedia_en/images/5/50/Shared_Design.png",
		rarity: ItemRarities.EQUIPMENT,
	},
	"aspect_lightning": {
		name: "Silence Between Two Strikes",
		description: [
			"sta::Become an aspect of lightning. ",
			"br::",
			"gra::Always active.",
			"br::",
			"gra::50% of holder's health is replaced with shield. Holder's attacks attach a delayed bomb that explodes for 50% damage",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/0/0a/Silence_Between_Two_Strikes.png",
		rarity: ItemRarities.EQUIPMENT,
	},
	"aspect_incorporeal": {
		name: "Spectral Circlet",
		description: [
			"sta::Become an aspect of incorporeality. ",
			"br::",
			"gra::Always active.",
			"br::",
			"gra::Nearby allies are cloaked. Holder's attacks apply an 80% slow on hit",
		],
		image_url: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/d/d2/Spectral_Circlet.png",
		rarity: ItemRarities.EQUIPMENT,
	},
}
