const whiteItems: string[] = [
	"ap_rounds",
	"backup_mag",
	"bison_steak",
	"fireworks",
	"bustling_fungus",
	"cautious_slug",
	"crowbar",
	"energy_drink",
	"focus_crystal",
	"gasoline",
	"lens_makers_glasses",
	"medkit",
	"monster_tooth",
	"goat_hoof",
	"personal_shield_gen",
	"armor_plate",
	"rusted_key",
	"soldiers_syringe",
	"sticky_bomb",
	"stun_grenade",
	"topaz_brooch",
	"tougher_times",
	"tritip_dagger",
	"warbanner",
	"item_scrap_white",
];

const greenItems: string[] = [
	"atg_missile",
	"bandolier",
	"berzerkers_pauldron",
	"chronobauble",
	"death_mark",
	"fuel_cell",
	"ghors_tome",
	"harvesters_scythe",
	"hopoo_feather",
	"infusion",
	"kjaros_band",
	"leeching_seed",
	"lepton_daisy",
	"old_guillotine",
	"old_war_stealthkit",
	"predatory_instincts",
	"razorwire",
	"red_whip",
	"rose_buckler",
	"runalds_band",
	"squid_polyp",
	"ukelele",
	"war_horn",
	"wax_quail",
	"item_scrap_green",
];

const redItems: string[] = [
	"57_leaf_clover",
	"aegis",
	"alien_head",
	"brainstalks",
	"brilliant_behemoth",
	"ceremonial_dagger",
	"defensive_microbots",
	"dios_best_friend",
	"frost_relic",
	"head_st",
	"happiest_mask",
	"hardlight_afterburner",
	"interstellar_desk_plant",
	"nkuhanas_opinion",
	"rejuv_rack",
	"resonance_disc",
	"sentient_meat_hook",
	"shattering_justice",
	"soulbound_catalyst",
	"tesla_coil",
	"wake_of_vultures",
	"item_scrap_red",
];

const lunarItems: string[] = [
	"beads_of_fealty",
	"brittle_crown",
	"corpsebloom",
	"defiant_gouge",
	"essence_of_heresy",
	"focused_convergence",
	"gesture_of_the_drowned",
	"hooks_of_heresy",
	"mercurial_rachis",
	"purity",
	"shaped_glass",
	"strides_of_heresy",
	"transcendence",
	"visions_of_heresy",
	"effigy_of_grief",
	"glowing_meteorite",
	"helfire_tincture",
	"spinel_tonic",
];

const bossItems: string[] = [
	"artifact_key",
	"charged_perforator",
	"empathy_cores",
	"genesis_loop",
	"halcyon_seed",
	"irradiant_pearl",
	"little_disciple",
	"mired_urn",
	"molten_perforator",
	"pearl",
	"planula",
	"queens_gland",
	"shatterspleen",
	"titanic_knurl",
	"item_scrap_yellow",
];

const equipment: string[] = [
	"blast_shower",
	"disposable_missile_launcher",
	"eccentric_vase",
	"foreign_fruit",
	"forgive_me_please",
	"fuel_array",
	"gnarled_woodsprite",
	"gorags_opus",
	"jade_elephant",
	"milky_chrysalis",
	"ocular_hud",
	"preon_accumulator",
	"primordial_cube",
	"radar_scanner",
	"recycler",
	"royal_capacitor",
	"sawmerang",
	"super_massive_leech",
	"the_backup",
	"the_crowdfunder",
	"volcanic_egg",
	"aspect_ice",
	"aspect_fire",
	"aspect_corruption",
	"aspect_perfection",
	"aspect_lightning",
	"aspect_incorporeal",
];

export const itemGroups: Record<string, string[]> = {
	"whiteItems": whiteItems,
	"greenItems": greenItems,
	"redItems": redItems,
	"bossItems": bossItems,
	"lunarItems": lunarItems,
	"equipment": equipment,
};